Resolve erro `rake routes`
NoMethodError: undefined method `name' for #<Array:0x007f8f99956700>
/Users/sue445/dev/workspace/github.com/sue445/gemoire/vendor/bundle/ruby/2.1.0/gems/padrino-core-0.12.3/lib/padrino-core/mounter.rb:112:in `block in named_routes'
/Users/sue445/dev/workspace/github.com/sue445/gemoire/vendor/bundle/ruby/2.1.0/gems/padrino-core-0.12.3/lib/padrino-core/mounter.rb:111:in `each'
/Users/sue445/dev/workspace/github.com/sue445/gemoire/vendor/bundle/ruby/2.1.0/gems/padrino-core-0.12.3/lib/padrino-core/mounter.rb:111:in `map'
/Users/sue445/dev/workspace/github.com/sue445/gemoire/vendor/bundle/ruby/2.1.0/gems/padrino-core-0.12.3/lib/padrino-core/mounter.rb:111:in `named_routes'
/Users/sue445/dev/workspace/github.com/sue445/gemoire/vendor/bundle/ruby/2.1.0/gems/padrino-core-0.12.3/lib/padrino-core/cli/rake_tasks.rb:35:in `list_app_routes'
/Users/sue445/dev/workspace/github.com/sue445/gemoire/vendor/bundle/ruby/2.1.0/gems/padrino-core-0.12.3/lib/padrino-core/cli/rake_tasks.rb:52:in `block (2 levels) in <top (required)>'